light:
  - angle-left
  - angle-right
  - buildings
  - cards-blank
  - cart-shopping
  - chart-line
  - check
  - credit-card
  - ellipsis-vertical
  - eye
  - gear
  - gem
  - list-check
  - location-dot
  - pencil
  - qrcode
  - store
  - tags
  - trash
  - user-ninja
  - users
  - users-line
  - wallet
regular:
  - angle-left