regular:
  - angle-left
  - angle-right
  - chart-line
  - check
  - ellipsis-vertical
  - eye
  - gear
  - list-check
  - location-dot
  - pencil
  - qrcode
  - store
  - tags
  - trash
  - user-ninja
  - users
  - users-line
  - wallet
